apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-frontend
  namespace: observability
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: ["devops-app"]
  selector:
    matchLabels:
      app: devops-app
      component: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
