apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-controller
  namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-ci
  namespace: jenkins
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-cd
  namespace: jenkins
