apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: devops-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: devops-app
      component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: devops-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: devops-app
      component: frontend
