apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: devops-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops-app
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-app
  labels:
    app: devops-app
    component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devops-app
      component: postgres
  template:
    metadata:
      labels:
        app: devops-app
        component: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: DB_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: DB_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_NAME } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "app"] }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["pg_isready", "-U", "app"] }
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-app
  labels:
    app: devops-app
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: devops-app
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
