apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: devops-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: devops-app
automountServiceAccountToken: false
