apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-app-readonly
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-readonly-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: devops-app-readonly
  apiGroup: rbac.authorization.k8s.io
