apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
